const houndsData = [
    {
        flag: "active",
        type: "boy",
        id: "charlie1935",
        cardTitle: "Charlie (1935)",
        attributes: "Male &#9679; 5 years old",
        description: "Greetings! My name is Charlie, I’m a handsome 5 year old basset hound & I guess you could say I’m retired! I prefer to sleep in every morning & once I do wake up, I’m very fun-loving but in no big hurry to get moving. At my foster home I enjoy a good rub down every morning, it helps me relax and feel at ease, it’s also helped me build trust with the people caring for me. I am housebroken, current on all vaccinations, neutered, HW negative and in good health. Eating alone is best for me and I’m not a big fan of sharing toys yet but I am learning! I am very smart, I know how to sit, walk on a leash, I enjoy daily walks with a few minutes of training & I know my name of course! I sleep on a comfy bed in my crate at night, everyone is safe that way because sometimes I’m startled upon waking because I have bad memories of a time when people weren’t always kind to me. I’m not into barking unless I see someone in the yard or the doorbell rings with a visitor. I do sometimes act silly and let out a little bark & a typical basset howl because I’m excited to see you when you come home. I’m also a perfect roommate as I’m considerate of the property of others & always go to the door to signal that I need to use the bathroom. I love to explore and sniff around outside & sunning in the grass is a favorite past time of mine so a fenced yard would be something that makes me so happy! I can join a home with adults only who are willing to continue training that will help me grow & learn to trust. I need a patient, loving, understanding home with structure & no other pets. If you’re willing to help me overcome my fears I know we can become the best of buddies & I could finally have my forever home! Until then I’ll be waiting patiently in my foster home working on my training so I can show you what a good boy I really am! Luv, Charlie",
        imgOne: "./charlie/Charlie1935_05.jpg",
        images: ["./charlie/Charlie1935_02.jpg", "./charlie/Charlie1935_03.jpg", "./charlie/Charlie1935_04.jpg"],
        // imgTwo: "./charlie/Charlie1935_02.jpg",
        // imgThree: "./charlie/Charlie1935_03.jpg",
        // imgFour: "./charlie/Charlie1935_04.jpg",
        adopt: "../adoptionApplication/adoptionApplication.html",
        adopted: "**Adopted**",
        status: "forever",
        label: "Forever",
        tooltip: "These bassets will remain with their foster family for the rest of their life where they will receive the care, comfort and love they deserve. They may have been diagnosed with serious or terminal illness, or may have behavioral needs best met by staying in their foster home."
    },
    {
        flag: "active",
        type: "girl",
        id: "reba1921",
        cardTitle: "Reba (1921)",
        attributes: "Female &#9679; 8 years old",
        description: "My name is Reba. The humans think I am about 8 years young. I have been with my foster family for 3 months now. If you were to ask them, I am sure they would say great things about me. I am very shy and scared of meeting new families. I don't remember my past family but I think I may have been ignored or mistreated. It has taken the last few months to understand love and affection. My foster daddy has been so good to me. He lets me sleep wherever I wish. Mostly I like to snuggle up to him on his bed. I get along well with my fellow doggies in the house. Everyone is so nice to me. I don't mind cats or children either. I have no food aggression, but at my house we each eat from our own bowls. I usually finish first. I am currently undergoing heartworm treatment but I should be available for adoption in a month or so. Note from my Foster Daddy: Reba is super sweet and loves attention. As you can tell, she does not have much Basset in her, but boy how she steals the hearts of everyone she meets. She has taken the last 3 months to gain her trust. I think the right loving family would be a good fit for her. She does get fed twice a day and likes to wake me up with nudging @ 7am or so, for her morning feeding. She does have full freedom of the human bed, couches and doggie beds. She learned the doggie door right away and has never had an accident in the house. She is super sweet and deserves the best family that will love her until the day she departs this world.",
        imgOne: "./reba/reba.jpg",
        imgTwo: "./reba/reba2.jpg",
        imgThree: "./reba/reba3.jpg",
        imgFour: "./reba/reba4.jpg",
        adopt: "../adoptionApplication/adoptionApplication.html",
        adopted: "",
        status: "available",
        label: "Available",
        tooltip: "These bassets are currently available for adoption. They are patiently waiting in their foster home until their forever home can be found."
    },
    {
        flag: "active",
        type: "girl",
        id: "sarah1869",
        cardTitle: "Sarah (1869)",
        attributes: "Female &#9679; 7 years old &#9679; Tricolor",
        description: "Sarah is a 7-year-old tricolor female. Prior to coming to SBR, Sarah was owned by a breeder and kept in an outdoor kennel. Sarah had chronic ear infections. After over a year of treatment with a dermatologist it was determined a total ear canal ablation for both ears. Prior to the surgery Sarah did not like riding in a car. Sarah was skittish around people. She would bark, pace and drool when unknown people were around. Sarah kept to herself in the foster home. After surgery Sarah is a different dog. The follow up vet appointment after surgery started with Sarah not wanting to go in the car. Once in the car Sarah was quiet and sat in one place looking out the window. At the surgeon’s office she walked right up to him, and he started petting her. The dr. called his staff in to see what a change the surgery had made. Sarah is more affectionate now and nose bumps faces and occasionally you get a lick. Sarah has some hearing, but it is like us listening under water, doggie door right away and has never had an accident in the house. She is super sweet and deserves the best family that will love her until the day she but does come when calling her name. Sarah is fine with other dogs but does not interact which is a product of being with the breeder. In time it may change. Sarah loves treats. Sarah weighs 55 pounds. She walks well on a leash. If Sarah does not eat right away it is because she plans to clean all the other dog’s bowls before eating her meal. Sarah’s foster mom says she is Basset smart, has her own quirks and will literally wiggle her way into your heart once she feels safe with you. If you are the forever home Sarah is looking for, please submit your application today.",
        imgOne: "./sarah/sarah1869_04.jpg",
        imgTwo: "./sarah/sarah1869_02.jpg",
        imgThree: "./sarah/sarah1869_03.jpg",
        imgFour: "./sarah/sarah1869_06.jpg",
        adopt: "../adoptionApplication/adoptionApplication.html",
        adopted: "",
        status: "notCleared",
        label: "Not Cleared",
        tooltip: "These bassets are awaiting vet visits for vaccinations, heartworm test and/or spaying and neutering. They are also under evaluation by their foster homes to learn the basset’s personality and needs."
    },
    {
        flag: "active",
        type: "boy",
        id: "rusty1727",
        cardTitle: "Rusty (1727)",
        attributes: "Male &#9679; 8 years old",
        description: "What a gorgeous hunk Rusty is! He is a sweet and active 8 year old boy who likes other dogs but will hog all the attention. He walks well on a leash but you need a strong hand when it comes to meeting other dogs on a walk; can be very loud when approaching other dogs. He LOVES walks and they are very necessary to tire him out for sleeping at night. Although Rusty gets along with dogs his size, he would be fine as an only dog also - just make sure that he gets plenty of exercise and attention. Rusty MUST be fed separately and not allowed to roam when other dogs in the house are eating as he does have food aggression. He will try and steal your food also, so best to keep him separated when you are eating. NO small children for Rusty’s new home as he does have a bite history He has worked with a trainer on getting things from him that he shouldn’t have, so best if children in the home are older (or no children) who understand and can Rusty’s space with his issues/ food aggression. Rusty will need to continue to remain on his prescription food, as well as needs his allergy shots and take a daily joint supplement in order to stay healthy. Average monthly cost for these items are approx. $75. Rusty is housebroken but NEEDS a consistent schedule. The crate has been very good for him. His new family must understand that he goes out immediately after meals and playtime. Rusty does wear a belly band in the house to discourage marking inside. ** If you have the perfect home for Rusty, please fill out an Adoption Application.",
        imgOne: "./rusty/Rusty1727_thumb.jpg",
        imgTwo: "./rusty/Rusty1727_02.jpg",
        imgThree: "./rusty/Rusty1727_03.jpg",
        imgFour: "./rusty/Rusty1727_01.jpg",
        adopt: "../adoptionApplication/adoptionApplication.html",
        adopted: "",
        status: "uk-hidden",
        label: "",
        tooltip: ""
    },
    {
        flag: "active",
        type: "forever",
        id: "chloe1520",
        cardTitle: "Chloe (1520)",
        attributes: "Female &#9679; 8 years old &#9679; Virtual",
        description: "Meet Chloe, an 8 year old girl who is small at 45 pounds. Chloe was recently diagnosed with lymphoma cancer but she doesn’t let that stop her from her loving personality that includes children, dogs and yes even cats. She loves going for walks and car rides. Riding shotgun is her preferred location! This sweet angel is housebroken and uses her doggy door too. Chloe is on a constant treatment of prednisone to help keep her cancer at bay. As we all know cancer sucks! No matter human or animal and no being deserves to go through it alone. That is where SBR has stepped in to give this innocent the loving home she deserves for the remainder of whatever life she has left. SBR will continue with her treatments and medical care to ensure she maintains a quality of life. Her foster family will continue to give her the unconditional love all animals deserve. If Chloe’s story has touched your heart or soul in some way and you want to help, please consider a “virtual” adoption by donating to Chloe’s care.",
        imgOne: "./chloe/chloe.jpg",
        imgTwo: "./chloe/chloe2.jpg",
        imgThree: "./chloe/chloe3.jpg",
        imgFour: "./chloe/chloe4.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Chloe+(1520)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "available",
        tooltip: "Tooltip Available"
    },
    {
        flag: "active",
        type: "forever",
        id: "kelly1282",
        cardTitle: "Kelly (1282)",
        attributes: "Female &#9679; Virtual",
        description: "Kelly is a tiny little Basset. She has a curved front leg that gives her a funny walk. She is very sweet and can be feisty with her foster brothers and sisters. Unfortunately, Kelly came from a bad situation and was probably kept outside. It has taken her foster family several years to get her to come in the house without prompting. She also suffers from severe storm anxiety and is petrified of loud noises. She takes medicine to help her anxiety. She has come a long way over the last couple of years. She has gained some confidence in public settings when she is with her foster pack. She is very sweet and loving. Kelly and Snickers came from the same setting and are very attached. While they love the pack, they find comfort with each other. They even eat together out of the same food bowl! Her foster parents have decided that Kelly and Snickers will stay with them forever. Through virtual adoption you can help to cover the on-going costs of keeping Kelly and Snickers with a loving family that will continue to shower love and security on them both.",
        imgOne: "./kelly/kelly.jpg",
        imgTwo: "./kelly/kelly2.jpg",
        imgThree: "./kelly/kelly3.jpg",
        imgFour: "./kelly/kelly4.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Kelly+(1282)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "uk-hidden",
        tooltip: ""
    },
    {
        flag: "active",
        type: "forever",
        id: "louie1435",
        cardTitle: "Louie (1435)",
        attributes: "Male &#9679; 7 or 8 years old &#9679; Virtual",
        description: "Louie is a sweet 7-8 year old guy who loves his neck and chin rubbed. He is very good with other dogs. He loves going for walks and really loves going to the pet stores. He is so well mannered and only barks when you are out of his site. He is good about his bath, nail trim and ear cleaning. He is also housebroken. Louie was diagnosed with EPI (Exocrine Pancreatic Insufficiency) and Diabetes. This means that Louie must have prescription enzymes mixed in with his meals and he takes insulin shots twice a day. He eats prescription dog food and takes Vestulin (animal specific insulin from the vet). Due to the EPI, Louie has a hard time gaining weight, so he will always be on the skinny side. Additionally, Louie has developed cataracts from the Diabetes. He has some vision, but he does have a hard time seeing. He has learned to compensate for his disability and moves around fairly well, but does bump into people and other dogs occasionally. Louie doesn’t mind getting his daily shots and will wait for his “after shot” treats. Louie will require regular vet visits to have his Glucose Curve done. This allows the vet to adjust his daily insulin injections. Also, he does require prescription food, enzymes, and insulin. He will need access to fresh water and the ability to go to the bathroom after drinking water, as the Diabetes tends to make him thirsty. Don’t let his health issues deter you from considering Louie. He is a wonderful boy and deserves a forever home!",
        imgOne: "./louie/louie.jpg",
        imgTwo: "./louie/louie2.jpg",
        imgThree: "./louie/louie3.jpg",
        imgFour: "./louie/louie4.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Louie+(1435)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "uk-hidden",
        tooltip: ""
    },
    {
        flag: "active",
        type: "forever",
        id: "rebel1650",
        cardTitle: "Rebel (1650)",
        attributes: "Male &#9679; Bonded Pair &#9679; Big Fluffy &#9679; Virtual",
        description: "Rebel is the other 1/2 of a BONDED pair with Dixie. Rebel is a BIG fluffy boy. He's very laid back and has shown no aggression. Rebel loves meeting people and walks well on the leash. Despite using the doggie door he hasn't grasped the idea he's supposed to go potty outside, not even while on walks, so does have occasional indoor accidents Rebel’s tail is almost always wagging. He can be a bit vocal at times. Dixie and Rebel are both very sweet, lovable dogs. Rebel is loved and cared for by his forever foster Mom. Your sponsorship of Rebel helps him get the medical treatment he needs.",
        imgOne: "./rebel/rebel.jpg",
        imgTwo: "./rebel/rebel2.jpg",
        imgThree: "./rebel/rebel.jpg",
        imgFour: "./rebel/rebel2.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Rebel+(1650)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "uk-hidden",
        tooltip: ""
    },
    {
        flag: "active",
        type: "forever",
        id: "snickers1314",
        cardTitle: "Snickers (1314)",
        attributes: "Male &#9679; Virtual",
        description: "Snickers is a good-looking Basset with an Elvis lip and a curved tail. He has developed quite the personality over the last couple of years. Unfortunately, Snickers came from the same bad situation as Kelly. He is very fearful of strangers. At times, mere eye contact can scare him. His foster family is very sensitive to his anxiety and have learned to work around his quirks. Snickers has grown very fond of his foster dad and will jump on the bed to lay down next to him. Snickers loves to go for his daily walks with his foster pack. His foster parents have to be very careful in public with him because he tends to be a runner and will try to pull out of his collar. While he loves his pack, Snickers and Kelly find comfort with each other. They even eat together out of the same food bowl! His foster parents have decided that Kelly and Snickers will stay with them forever. Through virtual adoption you can help to cover the on-going costs of keeping Kelly and Snickers with a loving family that will continue to shower love and security on them both.",
        imgOne: "./snickers/snickers.jpg",
        imgTwo: "./snickers/snickers2.jpg",
        imgThree: "./snickers/snickers5.jpg",
        imgFour: "./snickers/snickers6.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Snickers+(1314)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "uk-hidden",
        tooltip: ""
    },
    {
        flag: "active",
        type: "forever",
        id: "sophie1485",
        cardTitle: "Sophie (1485)",
        attributes: "Female &#9679; Virtual",
        description: "Our foster girl Sophie has proven to be an absolute sweetheart. She came into Suncoast Basset Rescue with a cyst that takes up a great deal of her spine. The cyst leaves her weak and wobbly in her hind end and delays messages to her brain when she has to potty. With all that said, she is one of the happiest, playful, loving houndies we've ever met! Nothing keeps this girl from enjoying her life with her foster brother & sister. She loves toys, chew bones and is happy to share them. She is on long life medications for pain and is a trooper when taking them. Sophie has found her forever foster home to be a safe , loving environment where she can get all the attention & love she needs. With her issues, it's best for her to remain in SBR'S care . Please consider being virtual adopter to help provide Sophie with the medical care she needs",
        imgOne: "./sophie/sophie.jpg",
        imgTwo: "./sophie/sophie2.jpg",
        imgThree: "./sophie/sophie3.jpg",
        imgFour: "./sophie/sophie4.jpg",
        adopt: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=paypal@suncoastbassetrescue.org&lc=US&item_name=Virtual+Adoption+Pledge+for+Sophie+(1485)&no_note=0&cn=&currency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted",
        adopted: "",
        label: "uk-hidden",
        tooltip: ""
    },
]